version: '2'

services:
  rails:
    container_name: ${RAILS_NAME}
    restart: always
    image: daprejean/rails:latest
    volumes:
    - ./railsApp:/railsApp
    ports:
    - "${RAILS_EXTERNAL_PORT}:3000"
    environment:
    - RAILS_ENV=${RAILS_RUN_ENV}
    - SECRET_KEY_BASE=${RAILS_SECRET_KEY_BASE}
    - http_proxy=${HTTP_PROXY}
    - https_proxy=${HTTPS_PROXY}
    - LOCAL_USER_ID=${LOCAL_USER_ID}
    - LOCAL_GROUP_ID=${LOCAL_GROUP_ID}
    - RAILS_DEV_DB_USER=${RAILS_DEV_DB_USER}
    - RAILS_DEV_DB_PASS=${RAILS_DEV_DB_PASS}
    - RAILS_STAG_DB_USER=${RAILS_STAG_DB_USER}
    - RAILS_STAG_DB_PASS=${RAILS_STAG_DB_PASS}
    - RAILS_PROD_DB_USER=${RAILS_PROD_DB_USER}
    - RAILS_PROD_DB_PASS=${RAILS_PROD_DB_PASS}
